"""init

Revision ID: 94270038b5e5
Revises: 074469488d05
Create Date: 2023-04-24 11:37:59.239924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94270038b5e5'
down_revision = '074469488d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_date', sa.String(length=255), nullable=False))
        batch_op.drop_column('release_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_data', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('release_date')

    # ### end Alembic commands ###
